# Generated by Django 4.2.1 on 2023-07-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer'),
        ('store', '0012_remove_product_images_crop_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.coupon'),
        ),
    ]
