# Generated by Django 4.2.2 on 2023-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_category_decs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_imgage',
            field=models.ImageField(blank=True, upload_to='photos/categories'),
        ),
    ]
