# Generated by Django 4.2.2 on 2023-06-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_brand_brand_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_imgage',
            new_name='cat_image',
        ),
    ]
