# Generated by Django 4.2.1 on 2023-07-19 07:00

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=15)),
                ('min_amount', models.PositiveBigIntegerField()),
                ('off_percent', models.PositiveIntegerField()),
                ('max_discount', models.PositiveBigIntegerField()),
                ('expiry_date', models.DateField(validators=[offers.models.validate_expiry_date])),
            ],
        ),
    ]
