# Generated by Django 4.2.1 on 2023-07-20 13:00

from django.db import migrations, models
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(validators=[offers.models.validate_expiry_date]),
        ),
    ]
