# Generated by Django 4.2.1 on 2023-06-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'accepted')], default='pending', max_length=20),
        ),
    ]
