# Generated by Django 4.2.1 on 2023-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_payment_payment_id_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
